# **Google Colab және Python орталарымен танысу**

# Notebooks

ML-де жаттығудың негізгі тәсілі ретінде Google Colab пайдаланамыз. Colab ноутбуктерді бұлтта алдын ала орнатпай-ақ тегін іске қосуға мүмкіндік береді, сонымен бірге [GPUs](https://en.wikipedia.org/wiki/Graphics_processing_unit) мүмкіндіктерін пайдаланмыз.

Google Colab код жазуға және орындауға мүмкіндік беретін блокнот деп аталатын интерактивті орта. Блокноттар бір немесе бірнеше Python нұсқауларының блоктары болып табылатын код ұяшықтарынан тұрады.

Мысалы, мұнда есептеу нәтижесін (күндегі секундтар санын) айнымалыда сақтайтын және оның мәнін басып шығаратын код ұяшығы берілген:

In [ ]:
a = 24 * 60 * 60
b = a * 7
c= a * 365
a , b , c

(86400, 604800, 31536000)

Бір ұяшықта анықтаған айнымалыларды кейінірек басқа ұяшықтарда пайдалануға болады:

seconds_in_a_week = 7 * seconds_in_a_day
seconds_in_a_week

# **Жаттығу**

Осы ұяшықтың астына ұяшық қосыңыз: осы ұяшықты басыңыз, содан кейін «+ Код» түймесін басыңыз. Жаңа ұяшықта *seconds_in_a_day* айнымалысын қайта пайдалану арқылы бір жылдағы секундтар санын есептеп, көрсетіңіз. Жаңа ұяшықты іске қосыңыз.

In [ ]:
seconds_in_a_day = a
seconds_in_a_year = 365 * seconds_in_a_day
seconds_in_a_year

31536000

**Орындау тәртібі маңызды екенін ескеріңіз.** Мысалы, *seconds_in_a_day* сақтайтын ұяшықты алдын ала іске қоспасақ, жоғарыдағы ұяшық қатені тудырады, себебі ол осы айнымалыға байланысты.

# Colab туралы көбірек оқу үшін осы сілтемені қараңыз
# **СӨЖ** https://colab.research.google.com/notebooks/intro.ipynb#scrollTo=-Rh3-Vt9Nev9

## **Python**

Python - академиялық ортада да, өнеркәсіпте де машиналық оқытуға арналған ең танымал бағдарламалау тілдерінің бірі. Бұл бөлімде біз Python негіздерін қарастырамыз.

## Арифметикалық операторлар

Python-да +- (қосу-азайту), * (көбейту), / (бөлу), ** (дәрежеге шығару), // (бүтін санды бөлу) арифметиалық амалдары орындалады.

## Tізімдер (Lists)

**Тізімдер** - элементтердің реттелген тізбектеріне арналған контейнер түрі. Тізімдерді бос етіп инициализациялауға болады.

In [ ]:
my_list = []

немесе кейбір бастапқы элементтермен

In [ ]:
my_list = [1, 2, 3]

Тізімдердің динамикалық өлшемі бар және оларға ***append*** арқылы қосуға болады

In [ ]:
my_list.append(4)
my_list

[1, 2, 3, 4]

Біз тізімнің жеке элементтеріне де қол жеткізе аламыз (индекстеу 0-ден басталады)

In [ ]:
my_list[2]

3

Тізімнің «бөліктеріне» my_list[i:j] командасын пайдаланып та қол жеткізе аламыз, мұндағы i – бөліктің басы (тағы да индекстеу 0-ден басталады) және `j – бөліктің соңы. Мысалы:

In [ ]:
my_list[1:3]

[2, 3]

Екінші индексті өткізіп жіберу бөлік тізімнің соңына дейін жұмыс істеуі керек дегенді білдіреді

In [ ]:
my_list[1:]

[2, 3, 4]

Элементтің тізімде бар-жоғын `in` арқылы тексере аламыз

In [ ]:
5 in my_list

False

Тізімнің ұзындығын `len` функциясын пайдаланып алуға болады

In [ ]:
len(my_list)

4

## Жолдар (Strings)

Мәтінді сақтау үшін жолдар қолданылады. Оларды бір тырнақша немесе қос тырнақша арқылы бөлуге болады

In [ ]:
string1 = "some text"
string2 = 'some other text'

Жолдар тізімдерге ұқсас әрекет етеді. Осылайша, біз жеке элементтерге дәл осылай қол жеткізе аламыз.

In [ ]:
string1[3]

және сол сияқты кесінділер үшін де тізімдермен бірдей

In [ ]:
string1[5:]

Жолдарды біріктіру `+` операторын пайдаланып орындалады

In [ ]:
string1 + " " + string2

## Шартты белгілер

Атауынан көрініп тұрғандай, шартты белгілер шарттың True немесе False болуына байланысты кодты орындау тәсілі болып табылады. Басқа тілдердегідей, Python тілі `if` және `else` тілдерін қолдайды, бірақ `else if` тілі `elif` тіліне қысқартылған, мұны төмендегі мысалдан көруге болады.

In [ ]:
my_variable = 5
if my_variable < 0:
  print("negative")
elif my_variable == 0:
  print("null")
else: # my_variable > 0
  print("positive")

positive

Мұндағы `<` және `>` – қатаң `кіші` және `үлкен` операторлары, ал `==` – теңдік операторы (айнымалыны тағайындау операторы `=`-мен шатастырмау керек). `<=` және `>=` операторларын `кіші` немесе `тең` салыстырулары үшін пайдалануға болады.

Басқа тілдерден айырмашылығы, код блоктары шегініс арқылы бөлінеді. Мұнда біз 2 бос орын шегінісін қолданамыз, бірақ көптеген бағдарламашылар 4 бос орын шегінісін де пайдаланады. Кодыңызда біркелкілік сақталған жағдайда кез келгені жарайды.

## Циклдер (Loops)

Циклдер – код блогын бірнеше рет орындау тәсілі. Циклдердің екі негізгі түрі бар: while және for циклдері.

While циклі

In [ ]:
i = 0
while i < len(my_list):
  print(my_list[i])
  i += 1 # equivalent to i = i + 1

NameError: name 'my_list' is not defined

For циклі

In [ ]:
for i in range(len(my_list)):
  print(my_list[i])

Егер мақсат тізім бойынша итерация жасау болса, біз мұны келесідей тікелей жасай аламыз

In [ ]:
for element in my_list:
  print(element)

## Функциялар (Functions)

Кодты оқу мүмкіндігін жақсарту үшін кодты нақты әрекеттерді орындауға жауапты әртүрлі блоктарға бөлу функциялар арқылы орындалады.

Функция кейбір кірістерді қабылдайды және кейбір шығыстарды қайтару үшін оларды өңдейді.

In [ ]:
def square(x):
  return x ** 2

def multiply(a, b):
  return a * b

# Functions can be composed.
square(multiply(3, 2))

36

Кодтың оқылуын жақсарту үшін кейде аргументтерді нақты атау пайдалы

**Жаттығу 1.** Шартты пайдаланып, [relu](https://en.wikipedia.org/wiki/Rectifier_(neural_networks)) функциясын жазыңыз

$\text{relu}(x) = \left\{
   \begin{array}{rl}
     x, & \text{if }  x \ge 0 \\
     0, & \text{otherwise }.
   \end{array}\right.$

In [ ]:
def relu(x):
  if x >= 0:
    return x
  else:
    return 0


relu(-3)

0

**Жаттығу 2.** for циклін пайдаланып, тізімдегі сандардың квадраттарының қосындысын есептейтін функция жазыңыз.

---



---

In [ ]:
def sum_of_squares(numbers):
   a=0
   for i in range(len(numbers)):
      a=a+numbers[i]**2

   return a



my_numbers = [5, 5, 5, 5]
sum_of_squares(my_numbers)

100

**Жаттығу 3.** For циклін және шартты амалды пайдаланып, вектордағы ең үлкен мәнді қайтаратын функция жазыңыз.

In [ ]:
def find_max(vector):
    max_val = vector[0]
    for num in vector:
        if num  max_val:
            max_val = num
    return max_val

my_vector = [3, 77, 2, 9, 5]
print(find_max(my_vector))

77

**Бонус жаттығу.** Егер уақыт мүмкіндік берсе, [көпіршікті сұрыптау](https://en.wikipedia.org/wiki/Bubble_sort) алгоритмін пайдаланып тізімді өсу ретімен (кішіден үлкеніне қарай) сұрыптайтын функция жазыңыз.

In [ ]:
def bubble_sort(my_list):
  # Write your function here
  return

my_list = [1, -3, 3, 2]
# Should return [-3, 1, 2, 3]
bubble_sort(my_list)

## СӨЖ

Әрине, бұл қысқа кіріспеде барлық тілдік ерекшеліктерді қамту мүмкін емес. Әрі қарай оқу үшін келесі ресурстарды ұсынамын:



*   List of Python [tutorials](https://wiki.python.org/moin/BeginnersGuide/Programmers)
* Four-hour [course](https://www.youtube.com/watch?v=rfscVS0vtbw) on Youtube

# Келесі сабақ тақырыбы:

# NumPy

* NumPy [reference](https://numpy.org/doc/stable/reference/)
* SciPy [lectures](https://scipy-lectures.org/)
*   One-hour [tutorial](https://www.youtube.com/watch?v=QUT1VHiLmmI) on Youtube

# Matplotlib

**Exercise 1.** Plot the relu and the [softplus](https://en.wikipedia.org/wiki/Rectifier_(neural_networks)#Softplus) functions on the same graph.

In [8]:
students = pd.DataFrame({
    "Аты": ["Айдана", "Алихан", "Дана"],
    "Жасы": [19, 20, 18],
    "Бағасы": [85, 92, 78]
})

students

      Аты  Жасы  Бағасы
0  Айдана    19      85
1  Алихан    20      92
2    Дана    18      78

In [9]:
students.head()

      Аты  Жасы  Бағасы
0  Айдана    19      85
1  Алихан    20      92
2    Дана    18      78

In [17]:
students.dtypes

Аты       object
Жасы       int64
Бағасы     int64
dtype: object

**Exercise 2.** Repeat the same scatter plot but using the [digits dataset](https://scikit-learn.org/stable/modules/generated/sklearn.datasets.load_digits.html) instead.